[package]
name = "cursor-modifier"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
uuid = { version = "1.2", features = ["v4"] }
dirs-next = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
